import { Component, computed, inject } from "@angular/core";
import { RouterLink } from "@angular/router";
import { LucideArrowRight, LucideHandshake, LucideHeartHandshake, LucideMapPin, LucideShieldCheck } from "@lucide/angular";
import { I18nService, type Locale } from "../i18n/i18n.service";

const ABOUT_COPY: Record<Locale, Record<string, string>> = {
  it: { title: "La tecnologia giusta nasce da una scelta umana.", lead: "Da Crotone all’Europa, selezioniamo tecnologia utile e accompagniamo ogni cliente con competenza reale.", cta: "Scopri la selezione", story: "La nostra storia", storyTitle: "Oltre vent’anni al servizio delle persone", p1: "Ekobit nasce nel 2006 e porta online un approccio semplice: conoscere i prodotti, ascoltare le necessità e proporre soltanto ciò che ha senso.", p2: "Il nuovo shop europeo unisce competenza italiana, informazioni chiare e assistenza raggiungibile in ogni fase.", v1: "Consulenza", v1t: "Confrontiamo funzioni, misure e reali necessità.", v2: "Affidabilità", v2t: "Trasparenza, garanzie e processi protetti.", v3: "Assistenza", v3t: "Restiamo presenti anche dopo l’acquisto.", v4: "Radici", v4t: "Una realtà italiana con una visione europea." },
  en: { title: "The right technology starts with a human choice.", lead: "From Crotone to Europe, we select useful technology and support every customer with real expertise.", cta: "Explore the selection", story: "Our story", storyTitle: "More than twenty years serving people", p1: "Founded in 2006, Ekobit brings a simple approach online: know the products, listen to needs and recommend only what makes sense.", p2: "The new European shop combines Italian expertise, clear information and accessible support at every stage.", v1: "Advice", v1t: "We compare functions, dimensions and real needs.", v2: "Reliability", v2t: "Transparency, guarantees and protected processes.", v3: "Support", v3t: "We remain available after purchase.", v4: "Roots", v4t: "An Italian business with a European vision." },
  fr: { title: "La bonne technologie commence par un choix humain.", lead: "De Crotone à l’Europe, nous sélectionnons une technologie utile avec une expertise réelle.", cta: "Voir la sélection", story: "Notre histoire", storyTitle: "Plus de vingt ans au service des personnes", p1: "Née en 2006, Ekobit suit une approche simple : connaître les produits, écouter et recommander seulement l’utile.", p2: "La nouvelle boutique européenne associe expertise italienne, informations claires et assistance accessible.", v1: "Conseil", v1t: "Nous comparons fonctions, dimensions et besoins réels.", v2: "Fiabilité", v2t: "Transparence, garanties et processus protégés.", v3: "Assistance", v3t: "Nous restons présents après l’achat.", v4: "Racines", v4t: "Une entreprise italienne avec une vision européenne." },
  de: { title: "Die richtige Technik beginnt mit einer menschlichen Entscheidung.", lead: "Von Crotone nach Europa wählen wir sinnvolle Technik aus und beraten mit echter Kompetenz.", cta: "Auswahl entdecken", story: "Unsere Geschichte", storyTitle: "Über zwanzig Jahre für Menschen", p1: "Ekobit wurde 2006 gegründet und folgt einem einfachen Ansatz: Produkte kennen, zuhören und nur Sinnvolles empfehlen.", p2: "Der neue Europa-Shop verbindet italienische Kompetenz, klare Informationen und erreichbaren Support.", v1: "Beratung", v1t: "Wir vergleichen Funktionen, Maße und echte Bedürfnisse.", v2: "Verlässlichkeit", v2t: "Transparenz, Gewährleistung und geschützte Abläufe.", v3: "Support", v3t: "Wir bleiben auch nach dem Kauf erreichbar.", v4: "Wurzeln", v4t: "Ein italienisches Unternehmen mit europäischer Vision." },
  es: { title: "La tecnología adecuada nace de una elección humana.", lead: "De Crotone a Europa, seleccionamos tecnología útil y acompañamos con experiencia real.", cta: "Ver la selección", story: "Nuestra historia", storyTitle: "Más de veinte años al servicio de las personas", p1: "Ekobit nació en 2006 con un enfoque sencillo: conocer los productos, escuchar y recomendar solo lo que tiene sentido.", p2: "La nueva tienda europea combina experiencia italiana, información clara y asistencia accesible.", v1: "Asesoramiento", v1t: "Comparamos funciones, medidas y necesidades reales.", v2: "Fiabilidad", v2t: "Transparencia, garantías y procesos protegidos.", v3: "Asistencia", v3t: "Seguimos presentes después de la compra.", v4: "Raíces", v4t: "Una empresa italiana con visión europea." },
};

@Component({
  imports: [RouterLink, LucideArrowRight, LucideHandshake, LucideHeartHandshake, LucideMapPin, LucideShieldCheck],
  templateUrl: "./about.page.html",
})
export class AboutPage {
  readonly i18n = inject(I18nService);
  readonly copy = computed(() => ABOUT_COPY[this.i18n.locale()]);
}
